module.exports = [
  "ADD_REACTIONS",
  "VIEW_CHANNEL",
  "SEND_MESSAGES",
  "READ_MESSAGE_HISTORY",
  "MANAGE_MESSAGES",
  "EMBED_LINKS",
  "USE_EXTERNAL_EMOJIS",
  "MENTION_EVERYONE",
  "ATTACH_FILES"
]